appName: minio-create-bucket-job

image:
  repository: minio-create-bucket-job

minio:
  url: "http://s3-minio-storage:9000"
  bucketName: "eca-service"
  createBucketInitialDelaySeconds: "60"
  secrets:
    name: secrets
  usernameSecretKey: MINIO_USERNAME
  passwordSecretKey: MINIO_PASSWORD