appName: rabbitmq

image:
  repository: rabbitmq
  tag: 3.8.14-management

container:
  amqpPort: 5672
  httpPort: 15672
  metricsPort: 15692

service:
  type: LoadBalancer
  amqpPort: 5672
  httpPort: 15672
  metricsPort: 15692

persistenceVolume:
  name: pv-rabbitmq
  capacity:
    storage: 5Gi
  storageClassName: standard
  hostPath: "/run/desktop/mnt/host/c/users/public/eca-service-k8s-volumes/rabbitmq"

persistenceVolumeClaim:
  name: pvc-rabbitmq
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard

rabbitmq:
  timezone: "Asia/Novosibirsk"