apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: {{ .Values.image.repository }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.container.port }}
              name: http
          env:
            - name: NGINX_PORT
              value: {{ .Values.container.port | quote }}
            - name: S3_MINIO_URL
              value: {{ .Values.minioProxy.minioUrl }}