= Развертывание filebeat в Kubernetes
:toc: macro

== Настройка filebeat

* В файле config/filebeat.yml указать настройки для сбора логов:

[source,yml]
----
filebeat.autodiscover:
  providers:
    - type: kubernetes
      node: ${NODE_NAME}
      hints.enabled: true
      # Выкл. сбора логов для всех подов
      hints.default_config.enabled: false
      parsers:
        - container: ~

output.elasticsearch:
  # Хост и порт elasticsearch для сохранения логов
  hosts: ['${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}']
  indices:
      # Название индекса в elasticsearch
    - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"
----

* В deployment вашего сервиса для включения сбора логов с помощью filebeat указать аннотации (annotations):

[source,yml]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  labels:
    app: spring-boot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
      annotations:
        # Вкл. чтение логов контейнера для filebeat
        co.elastic.logs/enabled: "true"
        # Вкл. парсинг логов контейнера в формате json
        co.elastic.logs/json.keys_under_root: "true"
        # Название поля, содержащее лог в формате json
        co.elastic.logs/json.message_key: "message"
----

== Запуск в Kubernetes

Для запуска alertmanager в Kubernetes необходимо из текущей директории выполнить команду:

  helm upgrade --install filebeat .

== Описание переменных values для helm chart

|===
|Переменная|Значение по умолчанию|Описание
|*appName*
|filebeat
|Название приложения (пода)
|*image.repository*
|elastic/filebeat
|Образ filebeat
|*image.tag*
|7.6.1
|Версия образа
|*filebeat.elastic.host*
|elasticsearch
|Хост elasticsearch для хранения логов
|*filebeat.elastic.port*
|9200
|Порт elasticsearch для хранения логов
|===
