groups:
  - name: eca-admin
    rules:
      - alert: ServiceDown
        expr: up == 0
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: 'Service {{ $labels.instance }} is unavailable.'
          description: '{{ $labels.instance }} has been down.'
      - alert: PostgreSQLDown
        expr: pg_up != 1
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: 'PostgreSQL {{ $labels.instance }} is unavailable.'
          description: '{{ $labels.instance }} has been down.'
      - alert: HeapUsageTooMuch
        expr: sum(jvm_memory_used_bytes{area="heap"}) by (instance) / sum(jvm_memory_max_bytes{area="heap"}) by (instance) * 100 > 70
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "JVM Instance {{ $labels.instance }} memory usage > 70%"
          description: "{{ $labels.instance }} has been in status [heap usage > 70%] for more than 1 minute. Current usage ({{ humanize $value }}%)"
      - alert: HeapUsageTooMuch
        expr: sum(jvm_memory_used_bytes{area="heap"}) by (instance) / sum(jvm_memory_max_bytes{area="heap"}) by (instance) * 100 > 80
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "JVM Instance {{ $labels.instance }} memory usage > 80%"
          description: "{{ $labels.instance }} has been in status [heap usage > 80%] for more than 1 minute. Current usage ({{ humanize $value }}%)"
      - alert: ProcessCpuUsageTooMuch
        expr: process_cpu_usage * 100 > 70
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "JVM Instance {{ $labels.instance }} cpu usage > 70%"
          description: "{{ $labels.instance }} has been in status [cpu usage > 70%] for more than 1 minute. CPU current usage ({{ humanize $value }}%)"
      - alert: ProcessCpuUsageTooMuch
        expr: process_cpu_usage * 100 > 80
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "JVM Instance {{ $labels.instance }} cpu usage > 80%"
          description: "{{ $labels.instance }} has been in status [cpu usage > 80%] for more than 1 minute. CPU current usage ({{ humanize $value }}%)"
      - alert: RabbitMQUnackedMessagesTooMuch
        expr: sum(rabbitmq_queue_messages_unacked) by (instance, rabbitmq_cluster) > 100
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Rabbit MQ instance {{ $labels.instance }} unacked messages > 100"
          description: "{{ $labels.instance }} has been in status [unacked messages > 100] for more than 1 minute. Current unacked messages ({{ humanize $value }})"
      - alert: SendingEmailMessagesErrorsIncreased
        expr: sum(increase(eca_mail_sending_message_error_total[1m])) by (instance) >= 5
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: "Sending email messages errors increased in instance {{ $labels.instance }}"
          description: "Sending email messages errors increased in the last minute. Total errors rate ({{ humanize $value }})"
      - alert: EcaErsRequestErrorsIncreased
        expr: sum(increase(feign_Client_http_response_code_total{status_group="5xx",host="eca-ers"}[5m])) by (instance) >= 4
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: "Ers request errors increased in instance {{ $labels.instance }}"
          description: "Ers request errors increased in the last 5 minutes. Total errors rate ({{ humanize $value }})"
      - alert: EcaMailRequestErrorsIncreased
        expr: sum(increase(feign_Client_http_response_code_total{status_group="5xx",host="eca-mail"}[5m])) by (instance) >= 4
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: "Eca mail request errors increased in instance {{ $labels.instance }}"
          description: "Eca mail request errors increased in the last 5 minutes. Total errors rate ({{ humanize $value }})"
      - alert: EcaAuditRequestErrorsIncreased
        expr: sum(increase(feign_Client_http_response_code_total{status_group="5xx",host="eca-audit-log"}[5m])) by (instance) >= 4
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: "Eca audit request errors increased in instance {{ $labels.instance }}"
          description: "Eca audit request errors increased in the last 5 minutes. Total errors rate ({{ humanize $value }})"
      - alert: S3RequestErrorsIncreased
        expr: sum(increase(s3_storage_request_error_total[5m])) by (instance) >= 4
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: "S3 request errors increased in instance {{ $labels.instance }}"
          description: "S3 request errors increased in the last 5 minutes. Total errors rate ({{ humanize $value }})"
      - alert: EcaWebPushRequestErrorsIncreased
        expr: sum(increase(feign_Client_http_response_code_total{status_group="5xx",host="eca-web-push"}[5m])) by (instance) >= 4
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: "Eca web push request errors increased in instance {{ $labels.instance }}"
          description: "Eca web push request errors increased in the last 5 minutes. Total errors rate ({{ humanize $value }})"
