global:
  scrape_interval: 30s
  evaluation_interval: 30s

rule_files:
  - 'alert-rules.yml'

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
  - job_name: 's3-minio-storage'
    metrics_path: '/minio/prometheus/metrics'
    static_configs:
      - targets: ['s3-minio-storage:9000']
  - job_name: 'discovery-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['discovery-server:8761']
  - job_name: 'service-discovery'
    http_sd_configs:
      - url: 'http://discovery-server:8761/api/prometheus/sd-configs'
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [__meta_discovery_app_name]
        target_label: application
      - source_labels: [__meta_discovery_app_instance_name]
        target_label: instance
      - source_labels: [__meta_discovery_app_instance_metrics_path]
        target_label: __metrics_path__
