appName: eca-data-loader

image:
  repository: eca-data-loader

env:
  OPENAPI_BASEPATH: "/eca-data-loader"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-db:5433/data_loader"
  SPRING_JPA_HIBERNATE_DDLAUTO: "validate"
  EUREKA_INSTANCE_PREFERIPADDRESS: "true"
  EUREKA_CLIENT_REGISTERWITHEUREKA: "true"
  EUREKA_CLIENT_FETCHREGISTRY: "true"
  JAVA_OPTS: "-Xmx384m"

secrets:
  SPRING_DATASOURCE_USERNAME: POSTGRES_USER
  SPRING_DATASOURCE_PASSWORD: POSTGRES_PASSWORD
  MINIO_ACCESSKEY: MINIO_USERNAME
  MINIO_SECRETKEY: MINIO_PASSWORD