apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
    tier: {{ .Values.appName }}
spec:
  completions: 1
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        tier: {{ .Values.appName }}
    spec:
      restartPolicy: Never
      containers:
        - name: {{ .Values.appName }}
          image: {{ .Values.image.repository }}
          imagePullPolicy: IfNotPresent
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.minio.usernameSecretKey }}
                  name: {{ .Values.minio.secrets.name }}
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.minio.passwordSecretKey }}
                  name:  {{ .Values.minio.secrets.name }}
            - name: BUCKET_NAME
              value: {{ .Values.minio.bucketName }}
            - name: S3_MINIO_URL
              value: {{ .Values.minio.url }}
            - name: CREATE_BUCKET_INITIAL_DELAY_SECONDS
              value: {{ .Values.minio.createBucketInitialDelaySeconds | quote }}