appName: postgres-db

image:
  repository: postgres
  tag: 13.9

container:
  port: 5432

service:
  type: LoadBalancer
  port: 5433

persistenceVolume:
  name: pv-postgresql
  capacity:
    storage: 5Gi
  storageClassName: standard
  hostPath: "/run/desktop/mnt/host/c/users/public/eca-service-k8s-volumes/postgres"

persistenceVolumeClaim:
  name: pvc-postgresql
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard

postgres:
  timezone: "Asia/Novosibirsk"
  secrets:
    name: secrets
  usernameSecretKey: POSTGRES_USER
  passwordSecretKey: POSTGRES_PASSWORD
  initDbScriptsSql: |
    ALTER SYSTEM SET max_connections = 500;
    create database eca;
    create database eca_oauth;
    create database mail;
    create database data_storage;
    create database eca_external_api;
    create database evaluation_results_storage;
    create database audit_log;
    create database eca_web_push;
    create database eca_load_tests;
    create database eca_auto_tests;
    create database eca_camunda;
    create database data_loader;