appName: postgres-db

image:
  repository: postgres
  tag: 13.9

container:
  port: 5432

service:
  type: LoadBalancer
  port: 5433

persistenceVolume:
  name: pv-postgresql
  capacity:
    storage: 5Gi
  storageClassName: standard
  hostPath: "/run/desktop/mnt/host/c/users/public/eca-service-k8s-volumes/postgres"

persistenceVolumeClaim:
  name: pvc-postgresql
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard

postgres:
  timezone: "Asia/Novosibirsk"
  secrets:
    name: secrets
  usernameSecretKey: POSTGRES_USER
  passwordSecretKey: POSTGRES_PASSWORD