{
 "title": "Eca - service dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Eca audit success requests / min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(feign_Client_http_response_code_total{application=\"eca-server\",host=\"eca-audit-log\",http_status=\"200\",method=\"sendEvent\"}[1m]) * 60) / 2) >= 0 OR on() vector(0)",
     "legendFormat": "eca-server"
    },
    {
     "expr": "(sum(rate(feign_Client_http_response_code_total{application=\"eca-oauth\",host=\"eca-audit-log\",http_status=\"200\",method=\"sendEvent\"}[1m]) * 60) / 2) >= 0 OR on() vector(0)",
     "legendFormat": "eca-oauth"
    },
    {
     "expr": "(sum(rate(feign_Client_http_response_code_total{application=\"eca-data-storage\",host=\"eca-audit-log\",http_status=\"200\",method=\"sendEvent\"}[1m]) * 60) / 2) >= 0 OR on() vector(0)",
     "legendFormat": "eca-data-storage"
    }
   ]
  },
  {
   "title": "Eca mail success requests / min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(feign_Client_http_response_code_total{application=\"eca-server\",host=\"eca-mail\",http_status=\"200\",method=\"sendEmail\"}[1m]) * 60) / 2) >= 0 OR on() vector(0)",
     "legendFormat": "eca-server"
    },
    {
     "expr": "(sum(rate(feign_Client_http_response_code_total{application=\"eca-oauth\",host=\"eca-mail\",http_status=\"200\",method=\"sendEmail\"}[1m]) * 60) / 2) >= 0 OR on() vector(0)",
     "legendFormat": "eca-oauth"
    }
   ]
  },
  {
   "title": "Ers requests time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(feign_Client_seconds_sum{application=\"eca-server\",host=\"eca-ers\",method=\"save\"}[1m]))/sum(rate(feign_Client_seconds_count{application=\"eca-server\",host=\"eca-ers\",method=\"save\"}[1m]))) >= 0 OR on() vector(0)",
     "legendFormat": "\"/api/save\" - AVG"
    },
    {
     "expr": "(max(feign_Client_seconds_max{application=\"eca-server\",host=\"eca-ers\",method=\"save\"})) >= 0 OR on() vector(0)",
     "legendFormat": "\"/api/save\" - MAX"
    },
    {
     "expr": "(sum(rate(feign_Client_seconds_sum{application=\"eca-server\",host=\"eca-ers\",method=\"getEvaluationResults\"}[1m]))/sum(rate(feign_Client_seconds_count{application=\"eca-server\",host=\"eca-ers\",method=\"getEvaluationResults\"}[1m]))) >= 0 OR on() vector(0)",
     "legendFormat": "\"/api/results\" - AVG"
    },
    {
     "expr": "(max(feign_Client_seconds_max{application=\"eca-server\",host=\"eca-ers\",method=\"getEvaluationResults\"})) >= 0 OR on() vector(0)",
     "legendFormat": "\"/api/results\" - MAX"
    },
    {
     "expr": "(sum(rate(feign_Client_seconds_sum{application=\"eca-server\",host=\"eca-ers\",method=\"getClassifierOptions\"}[1m]))/sum(rate(feign_Client_seconds_count{application=\"eca-server\",host=\"eca-ers\",method=\"getClassifierOptions\"}[1m]))) >= 0 OR on() vector(0)",
     "legendFormat": "\"/api/optimal-classifier-options\" - AVG"
    },
    {
     "expr": "(max(feign_Client_seconds_max{application=\"eca-server\",host=\"eca-ers\",method=\"getClassifierOptions\"})) >= 0 OR on() vector(0)",
     "legendFormat": "\"/api/optimal-classifier-options\" - MAX"
    }
   ]
  },
  {
   "title": "S3 requests time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(s3_storage_object_request_seconds_sum{application=\"eca-server\",method=\"uploadObject\"}[1m]))/sum(rate(s3_storage_object_request_seconds_count{application=\"eca-server\",method=\"uploadObject\"}[1m]))) >= 0 OR on() vector(0)",
     "legendFormat": "\"uploadObject\" - AVG"
    },
    {
     "expr": "(max(s3_storage_object_request_seconds_max{application=\"eca-server\",method=\"uploadObject\"})) >= 0 OR on() vector(0)",
     "legendFormat": "\"uploadObject\" - MAX"
    },
    {
     "expr": "(sum(rate(s3_storage_object_request_seconds_sum{application=\"eca-server\",method=\"getObject\"}[1m]))/sum(rate(s3_storage_object_request_seconds_count{application=\"eca-server\",method=\"getObject\"}[1m]))) >= 0 OR on() vector(0)",
     "legendFormat": "\"getObject\" - AVG"
    },
    {
     "expr": "(max(s3_storage_object_request_seconds_max{application=\"eca-server\",method=\"getObject\"})) >= 0 OR on() vector(0)",
     "legendFormat": "\"getObject\" - MAX"
    },
    {
     "expr": "(sum(rate(s3_storage_object_request_seconds_sum{application=\"eca-server\",method=\"getObjectPresignedProxyUrl\"}[1m]))/sum(rate(s3_storage_object_request_seconds_count{application=\"eca-server\",method=\"getObjectPresignedProxyUrl\"}[1m]))) >= 0 OR on() vector(0)",
     "legendFormat": "\"getObjectPresignedProxyUrl\" - AVG"
    },
    {
     "expr": "(max(s3_storage_object_request_seconds_max{application=\"eca-server\",method=\"getObjectPresignedProxyUrl\"})) >= 0 OR on() vector(0)",
     "legendFormat": "\"getObjectPresignedProxyUrl\" - MAX"
    }
   ]
  },
  {
   "title": "Ers success requests / min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(feign_Client_http_response_code_total{application=\"eca-server\",host=\"eca-ers\",http_status=\"200\",method=\"save\"}[1m]) * 60) / 2) >= 0 OR on() vector(0)",
     "legendFormat": "/api/save"
    },
    {
     "expr": "(sum(rate(feign_Client_http_response_code_total{application=\"eca-server\",host=\"eca-ers\",http_status=\"200\",method=\"getEvaluationResults\"}[1m]) * 60) / 2) >= 0 OR on() vector(0)",
     "legendFormat": "/api/results"
    },
    {
     "expr": "(sum(rate(feign_Client_http_response_code_total{application=\"eca-server\",host=\"eca-ers\",http_status=\"200\",method=\"getClassifierOptions\"}[1m]) * 60) / 2) >= 0 OR on() vector(0)",
     "legendFormat": "/api/optimal-classifier-options"
    }
   ]
  },
  {
   "title": "S3 request object memory total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(s3_storage_object_size_bytes_sum{application=\"eca-server\"}[1m]))/sum(rate(s3_storage_object_size_bytes_count{application=\"eca-server\"}[1m]))) >= 0 OR on() vector(0)",
     "legendFormat": "AVG size"
    },
    {
     "expr": "(max(s3_storage_object_size_bytes_max{application=\"eca-server\"})) >= 0 OR on() vector(0)",
     "legendFormat": "MAX object size"
    }
   ]
  },
  {
   "title": "Ers 5xx errors / min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(feign_Client_http_response_code_total{status_group=\"5xx\",host=\"eca-ers\",application=\"eca-server\"}[1m]) * 60) / 2) >= 0 OR on() vector(0)",
     "legendFormat": "eca-server"
    }
   ]
  },
  {
   "title": "S3 success requests / min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(s3_storage_request_success_total{application=\"eca-server\",method=\"uploadObject\"}[1m]) * 60) / 2) >= 0 OR on() vector(0)",
     "legendFormat": "uploadObject"
    },
    {
     "expr": "(sum(rate(s3_storage_request_success_total{application=\"eca-server\",method=\"downloadObject\"}[1m]) * 60) / 2) >= 0 OR on() vector(0)",
     "legendFormat": "downloadObject"
    },
    {
     "expr": "(sum(rate(s3_storage_request_success_total{application=\"eca-server\",method=\"getObjectPresignedUrl\"}[1m]) * 60) / 2) >= 0 OR on() vector(0)",
     "legendFormat": "getObjectPresignedProxyUrl"
    }
   ]
  },
  {
   "title": "Eca audit log 5xx errors / min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(feign_Client_http_response_code_total{status_group=\"5xx\",host=\"eca-audit-log\",application=\"eca-server\"}[1m]) * 60) / 2) >= 0 OR on() vector(0)",
     "legendFormat": "eca-server"
    },
    {
     "expr": "(sum(rate(feign_Client_http_response_code_total{status_group=\"5xx\",host=\"eca-audit-log\",application=\"eca-oauth\"}[1m]) * 60) / 2) >= 0 OR on() vector(0)",
     "legendFormat": "eca-oauth"
    },
    {
     "expr": "(sum(rate(feign_Client_http_response_code_total{status_group=\"5xx\",host=\"eca-audit-log\",application=\"eca-data-storage\"}[1m]) * 60) / 2) >= 0 OR on() vector(0)",
     "legendFormat": "eca-data-storage"
    }
   ]
  },
  {
   "title": "S3 error requests / min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(s3_storage_request_error_total{application=\"eca-server\",method=\"uploadObject\"}[1m]) * 60) / 2) >= 0 OR on() vector(0)",
     "legendFormat": "uploadObject"
    },
    {
     "expr": "(sum(rate(s3_storage_request_error_total{application=\"eca-server\",method=\"downloadObject\"}[1m]) * 60) / 2) >= 0 OR on() vector(0)",
     "legendFormat": "downloadObject"
    },
    {
     "expr": "(sum(rate(s3_storage_request_error_total{application=\"eca-server\",method=\"getObjectPresignedUrl\"}[1m]) * 60) / 2) >= 0 OR on() vector(0)",
     "legendFormat": "getObjectPresignedProxyUrl"
    }
   ]
  },
  {
   "title": "Mail error requests / min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(eca_mail_sending_message_error_total[1m]) * 60)) >= 0 OR on() vector(0)",
     "legendFormat": "mail_error_requests"
    }
   ]
  },
  {
   "title": "Eca mail 5xx errors / min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(feign_Client_http_response_code_total{status_group=\"5xx\",host=\"eca-mail\",application=\"eca-server\"}[1m]) * 60) / 2) >= 0 OR on() vector(0)",
     "legendFormat": "eca-server"
    },
    {
     "expr": "(sum(rate(feign_Client_http_response_code_total{status_group=\"5xx\",host=\"eca-mail\",application=\"eca-oauth\"}[1m]) * 60) / 2) >= 0 OR on() vector(0)",
     "legendFormat": "eca-oauth"
    }
   ]
  },
  {
   "title": "Eca web push success requests / min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(feign_Client_http_response_code_total{application=\"eca-server\",host=\"eca-web-push\",http_status=\"200\",method=\"sendPush\"}[1m]) * 60) / 2) >= 0 OR on() vector(0)",
     "legendFormat": "eca-server"
    }
   ]
  },
  {
   "title": "Eca web push 5xx errors / min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(feign_Client_http_response_code_total{status_group=\"5xx\",host=\"eca-web-push\",application=\"eca-server\"}[1m]) * 60) / 2) >= 0 OR on() vector(0)",
     "legendFormat": "eca-server"
    }
   ]
  }
 ]
}