appName: discovery-server

image:
  repository: discovery-server

container:
  port: 8761
  actuatorPort: 8761

service:
  type: LoadBalancer
  port: 8761
  actuatorPort: 8761

resources:
  limits:
    memory: 384Mi

env:
  JAVA_OPTS: "-Xmx256m -XX:MaxMetaspaceSize=256m"