appName: eca-server

image:
  repository: eca-server

env:
  OPENAPI_BASEPATH: "/eca-server"
  SPRING_DATASOURCE_JDBCURL: "jdbc:postgresql://postgres-db:5433/eca"
  SPRING_JPA_HIBERNATE_DDLAUTO: "validate"
  SPRING_CAMUNDA_JDBCURL: "jdbc:postgresql://postgres-db:5433/eca_camunda"
  SPRING_RABBITMQ_HOST: "rabbitmq"
  SPRING_RABBITMQ_PORT: "5672"
  QUEUE_EVALUATIONREQUESTQUEUE: "evaluation-request-queue"
  QUEUE_EVALUATIONOPTIMIZERREQUESTQUEUE: "evaluation-optimizer-request-queue"
  QUEUE_EXPERIMENTREQUESTQUEUE: "experiment-request-queue"
  SPRING_REDIS_HOST: "redis"
  SPRING_CACHE_TYPE: "redis"
  AUDIT_ENABLED: "true"
  AUDIT_ASYNCEVENTS: "true"
  AUDIT_THREADPOOLSIZE: "3"
  REDELIVERY_ENABLED: "true"
  LOCK_ENABLED: "true"
  LOCK_REGISTRYTYPE: "REDIS"
  USERPROFILE_CLIENT_CACHE_ENABLED: "true"
  USERPROFILE_CLIENT_CACHE_RABBIT_DATAEVENTEXCHANGENAME: "user-profile-options-exchange"
  USERPROFILE_CLIENT_CACHE_RABBIT_DATAEVENTQUEUE: "eca-server-user-profile-options-data-event-queue"
  EUREKA_INSTANCE_PREFERIPADDRESS: "true"
  EUREKA_CLIENT_REGISTERWITHEUREKA: "true"
  EUREKA_CLIENT_FETCHREGISTRY: "true"

secrets:
  SPRING_DATASOURCE_USERNAME: POSTGRES_USER
  SPRING_DATASOURCE_PASSWORD: POSTGRES_PASSWORD
  MINIO_ACCESSKEY: MINIO_USERNAME
  MINIO_SECRETKEY: MINIO_PASSWORD
  SPRING_RABBITMQ_USERNAME: RABBITMQ_USERNAME
  SPRING_RABBITMQ_PASSWORD: RABBITMQ_PASSWORD
