appName: eca-oauth

image:
  repository: eca-oauth

env:
  OPENAPI_BASEPATH: "/eca-oauth"
  AUDIT_ENABLED: "true"
  AUDIT_ASYNCEVENTS: "true"
  AUDIT_THREADPOOLSIZE: "3"
  REDELIVERY_ENABLED: "true"
  LOCK_ENABLED: "true"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-db:5433/eca_oauth"
  SPRING_JPA_HIBERNATE_DDLAUTO: "validate"
  SPRING_RABBITMQ_HOST: "rabbitmq"
  SPRING_RABBITMQ_PORT: "5672"
  USERPROFILE_RABBIT_EXCHANGENAME: "user-profile-options-exchange"
  EUREKA_INSTANCE_PREFERIPADDRESS: "true"
  EUREKA_CLIENT_REGISTERWITHEUREKA: "true"
  EUREKA_CLIENT_FETCHREGISTRY: "true"

secrets:
  SPRING_DATASOURCE_USERNAME: POSTGRES_USER
  SPRING_DATASOURCE_PASSWORD: POSTGRES_PASSWORD
  SPRING_RABBITMQ_USERNAME: RABBITMQ_USERNAME
  SPRING_RABBITMQ_PASSWORD: RABBITMQ_PASSWORD