apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
      annotations:
        # Enable fetch container logs for filebeat
        co.elastic.logs/enabled: "true"
        # Enable json logs for filebeat
        co.elastic.logs/json.keys_under_root: "true"
        # Add parse log error message
        co.elastic.logs/json.add_error_key: "true"
        # Json logs message field
        co.elastic.logs/json.message_key: "message"
    spec:
      containers:
        - name: {{ .Values.appName }}
          imagePullPolicy: IfNotPresent
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - name: http
              containerPort: {{ .Values.container.port }}
            - name: actuator
              containerPort: {{ .Values.container.actuatorPort }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.container.actuatorPort }}
            initialDelaySeconds: 120
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.container.actuatorPort }}
            initialDelaySeconds: 15
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: common-config
            - configMapRef:
                name: {{ .Values.appName }}
          env:
            {{- range $envVariable, $secretKey := .Values.secrets }}
            - name: {{ $envVariable }}
              valueFrom:
                secretKeyRef:
                  key: {{ $secretKey }}
                  name: secrets
            {{- end }}