apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.appName }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
  {{- if ne .Values.service.port .Values.service.actuatorPort }}
    - name: actuator
      port: {{ .Values.service.actuatorPort }}
      targetPort: {{ .Values.container.actuatorPort }}
  {{- end }}