apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.appName }}
  ports:
    - name: ui
      port: {{ .Values.service.uiPort }}
      targetPort: {{ .Values.container.uiPort }}
    - name: zipkin
      port: {{ .Values.service.zipkinPort }}
      targetPort: {{ .Values.container.zipkinPort }}