filebeat.autodiscover:
  providers:
    - type: kubernetes
      node: ${NODE_NAME}
      hints.enabled: true
      # Disabled fetch logs for all containers
      hints.default_config.enabled: false
      parsers:
        - container: ~

output.elasticsearch:
  hosts: ['http://${VICTORIALOGS_HOST}:${VICTORIALOGS_PORT}/insert/elasticsearch/']
  parameters:
    _msg_field: "message"
    _time_field: "@timestamp"
    _stream_fields: "application_name"
    ignore_fields: "tags,@version,agent*,ecs.version,log.offset,log.file*,level_value,input.type,host.name,container*,error.message,error.type,kubernetes.labels*,kubernetes.node*,kubernetes.namespace*,kubernetes.replicaset*"