apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}
data:
{{- if (.Files.Get "config/rabbitmq.conf") }}
  rabbitmq.conf: |
{{ (.Files.Get "config/rabbitmq.conf") | indent 4 }}
{{- end}}