apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      hostname: {{ .Values.appName }}
      containers:
        - name: {{ .Values.appName }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: amqp
              containerPort: {{ .Values.container.amqpPort }}
            - name: http
              containerPort: {{ .Values.container.httpPort }}
            - name: metrics
              containerPort: {{ .Values.container.metricsPort }}
          env:
            - name: TZ
              value: {{ .Values.rabbitmq.timezone }}
            - name: RABBITMQ_DEFAULT_VHOST
              value: {{ .Values.rabbitmq.vhost }}
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.rabbitmq.usernameSecretKey }}
                  name: {{ .Values.rabbitmq.secrets.name }}
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.rabbitmq.passwordSecretKey }}
                  name: {{ .Values.rabbitmq.secrets.name }}
          volumeMounts:
            - name: {{ .Values.persistenceVolumeClaim.name }}
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: {{ .Values.persistenceVolumeClaim.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistenceVolumeClaim.name }}