apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistenceVolume.name }}
spec:
  capacity:
    storage: {{ .Values.persistenceVolume.capacity.storage }}
  storageClassName: {{ .Values.persistenceVolume.storageClassName }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.persistenceVolume.hostPath }}