apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.appName }}
  ports:
    - name: amqp
      port: {{ .Values.service.amqpPort }}
      targetPort: {{ .Values.container.amqpPort }}
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.container.httpPort }}
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: {{ .Values.container.metricsPort }}