apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}
data:
{{- if (.Files.Get "config/alertmanager.yml") }}
  alertmanager.yml: |
{{ (.Files.Get "config/alertmanager.yml") | indent 4 }}
{{- end}}