apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          imagePullPolicy: IfNotPresent
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          args:
            - --config.file=/etc/alertmanager/alertmanager.yml
            - --web.external-url={{ .Values.alertmanager.webExternalUrl }}
          ports:
            - containerPort: {{ .Values.container.port }}
          env:
            - name: TZ
              value: {{ .Values.alertmanager.timezone }}
          volumeMounts:
            - name: alertmanager-config
              mountPath: /etc/alertmanager/alertmanager.yml
              subPath: alertmanager.yml
            - name: secrets-volume
              mountPath: /etc/secrets
      volumes:
        - name: alertmanager-config
          configMap:
            name: {{ .Values.appName }}
            items:
              - key: alertmanager.yml
                path: alertmanager.yml
        - name: secrets-volume
          secret:
            secretName: {{ .Values.alertmanager.secrets.name }}